### ISSUE TITLE
not support "Token Authentication"

### ISSUE THREAD

**Issue by thuzhf** [shmilee/scripts#2]
I encounter the follow error when I start the container according to your readme:
```
...
Next authentication is "Token Authentication"
But we don't support it
user "..." login FAILED!
 -> Enter 'XXX' to exit:
```
How can I solve this?

**Comment by shmilee** [comment]
It seems the 7.6.8 CLI-EC doesn't support "Token Authentication". (**But we don't support it**)
`easyconn login -h`  shows that  only username/password authentication  and certificate authentication are supportted. 

```
root@bc89fcea409b:/# /usr/share/sangfor/EasyConnect/resources/bin/easyconn login -h
Usage: easyconn login [OPTION]...
command to login vpn

  -h show options
  -d vpn address, make sure it's assigned and the format is right, like "199.201.73.191:443"
  -t login type, "pwd" means username/password authentication 
                 "cert" means certificate authentication 
  -u username
  -p password
  -c certificate path
  -m password for certificate
  -l certificate used to be authentication
```

You can try the GUI plan with the deb package provided by your organization.

**Comment by shmilee** [comment]
Closed (Duplicate)
https://github.com/Hagb/docker-easyconnect/issues/45#issuecomment-803262300
