### ISSUE TITLE
怎么编译easyconn_7.6.8.2-ubuntu_amd64.deb版本包

### ISSUE THREAD

**Issue by unfadedtrail** [shmilee/scripts#3]
@shmilee  你好，怎么编译easyconn_7.6.8.2-ubuntu_amd64.deb版本包？源码对外开放吗？

**Comment by Hagb** [comment]
见 https://github.com/Hagb/docker-easyconnect/issues/35#issuecomment-790597107

**Comment by unfadedtrail** [comment]
@Hagb 感谢回复！我看了https://github.com/Hagb/docker-easyconnect/issues/35#issuecomment-790597107 ，就是说这个版本包我们是没有源码的，也没有官网下载地址，是吗？“天河”指的是谁？

**Comment by shmilee** [comment]
这个版本，其他gui的版本都没有源码编译，都只有安装包的。
这个命令行版本，是从和课题组对接的天河负责人那要的，我没找到网上的下载地址。
我们用的机时还挺多的，可能他就认真对待了一下命令行这个需求。

**Comment by unfadedtrail** [comment]
@shmilee 感谢回复。
那这个命令行版本，能否作为深信服官方版本来使用？我这边也有需求要使用命令行版本，但是这个版本没有开源也没看到是深信服官方提供，所以不符合公司规范。。。或者，能否提供一下这个命令行版本中与深信服程序、VPN服务端的交互逻辑，我再重新搞个模拟程序也可以。。。搞定了的话也可以开源

**Comment by shmilee** [comment]
这个我没有哎，我们就只要了安装包，了解了如何使用，此外没其他需求。你这些需求是公对公吗？那可以公司以甲方去谈的嘛

如果是自己偷偷用，个人行为（不符合公司规范，也不想让公司知道？），那只能自力更生，找准问题自己解决了。
比如，为啥不符合公司规范，和公司服务器部署的版本不一致？这个可以尝试用命令行版本的程序+公司对应版本的conf。
其他必须用证书登录的问题，。。等就翻翻issue看看有没有能参考的吧，我很久没关注了。
要是公司部署定制的，那就难说了，如果只是路径上有问题，直接修改二进制文件对应的string可能就成了（这个情况属于我拿着答案出题目了，记得有个issue是十六进制替换实现了自己一个特殊需求）

**Comment by unfadedtrail** [comment]
不是偷偷用，要在公司内使用，登录客户的VPN。现在是尝试用命令行版本连接客户VPN，然后大家都通过这个命令行版本启动的客户端去访问客户的VPN网络，避免每个人都要登录VPN。同时又不是非这样不可，所以也没到要以甲方去谈的程度。但这又是很优的方案。。。现在这个命令行版本，能否当官方版本使用呢、、

**Comment by shmilee** [comment]
**避免每个人都要登录VPN**，重点是这个吧，docker -p 把端口暴露出来之后，hostIP别用127.0.0.1，用电脑内网IP，其他电脑以此IP为跳板访问，本质上大家都这么用的，除了debug时会到container中去。

**Comment by unfadedtrail** [comment]
重点没错，所以现在的疑问是这个命令行版本能否作为官方版本使用，能的话这个版本基本就可以满足需求了。或者完全开源、经过正规第三方认证啥的也可以

**Comment by shmilee** [comment]
安装包算官方版本的，但正规认证啥的不好办。
我分享的deb应该是，天河用户——天河(深信服用户)——深信服，这样的获取链。
我猜要做到符合公司规范，可能需要你向客户索要命令行版本的安装包，保留官方渠道的获取记录，应该没问题了吧。只是你的客户和深信服之间能不能成，不是你能控制的。此外再注意一下版本，至少7.6.8有命令行版本。

**Comment by unfadedtrail** [comment]
估计不好向客户索要，我这边只是客户的一个服务方，客户不只有一个服务方。也许可以直接向深信服要？不行的话，可能这条路要凉凉。。
